CREATE TABLE GroupChats (
    ChatId INT IDENTITY(1,1) PRIMARY KEY,
    ComplaintId INT NOT NULL FOREIGN KEY REFERENCES Complaints(ID) ON DELETE CASCADE,
    CreatedDate DATETIME DEFAULT GETDATE(),
    IsDeleted BIT DEFAULT 0
);