CREATE TABLE Evidence(
	Id INT PRIMARY KEY IDENTITY(1,1),
	ComplaintId INT,
	FilePath NVARCHAR(MAX),
	UploadDate DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (ComplaintId) REFERENCES Complaints(Id) ON DELETE CASCADE
);